const {
  SNOWPACK_PUBLIC_API_URL,
  SNOWPACK_PUBLIC_API_KEY,
  SNOWPACK_PUBLIC_IMG_URL,
} = import.meta.env;

export const API_URL = SNOWPACK_PUBLIC_API_URL;
export const API_KEY = SNOWPACK_PUBLIC_API_KEY;
export const IMG_URL = SNOWPACK_PUBLIC_IMG_URL;
